### ISSUE TITLE
map_dtc renames col names

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr3misc#8]
```
xs = list(a = data.table(foo = 1), b = data.table(bar = 2))
d = map_dtc(xs, identity)
print(d)
```

leads to
```
   a.foo b.bar
1:     1     2
```

this is pretty much always unwanted i guess. i would suggest to either always
unname the xs list, or have a flag for that, which is by default true

**Comment by mllg** [comment]
I think that this should throw an error. The elements to bind should be vectors, not data.tables.

**Comment by mllg** [comment]
OTOH, purrr allows this. 

I see no obvious or easy solution for this. Sometimes you want the "inner" names, sometimes the "outer" names. 

Unnaming `xs` would break this:
```r
xs = list(a = 1, b = 2)
d = map_dtc(xs, identity)
```

**Comment by berndbischl** [comment]
you solved it in this commit 3 days ago.
i added a further test to make sure

**Comment by berndbischl** [comment]
actually you didnt, an my test does test my issue. 
if the list is named, we still have the same problem

**Comment by berndbischl** [comment]
i want this solved, I will now at least compare what purrr does

**Comment by berndbischl** [comment]
purrr works, as I want it 
in both cases here, colnames "a" and "b" are created

library(purrr)
```
x1 = list(data.table(a = 1), data.table(b = 2))
x2 = list(foo = data.table(a = 1), bar = data.table(b = 2))

d1 = purrr::map_dfc(x1, identity)
print(d1)
d2 = purrr::map_dfc(x2, identity)
print(d1)
```

**Comment by berndbischl** [comment]
fixed NOW and added a test
I had to add a mini.map, in map_dtc, that slows the call down A BIT
but at least it works now

**Comment by mllg** [comment]
I did not fix because I was unsure about what behavior is wanted. Apparently we now just discard the "outer" names. I don't find it very intuitiv, but can live with it.

I've fixed your commit so that everything with a dimension works (i.e., data.frames and matrices).

**Comment by berndbischl** [comment]
> I did not fix because I was unsure about what behavior is wanted. Apparently we now just discard the "outer" names. I don't find it very intuitiv,

well in the OP is suggested exactly that. you never said you want something else 
(you said you wanted it to work with vectors, i then immediatly agreed)

also: we are now 100% in alignment with purrr. 
(that I posted today)
i thought we wanted exactly that?
